name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build Lean project
    steps:
      - uses: actions/checkout@v3
      - name: build project
        uses: leanprover-contrib/lean-build-action@master
